# Configuration File for Automatic Broadcasts

[delay]
    # The time between each broadcast in seconds
    # Default: 300
    # Minimum: 60
    delay = 300

[[broadcast]]
    # Add a click event to the message.
    # Supports: RUN_COMMAND, SUGGEST_COMMAND, OPEN_URL, COPY_TO_CLIPBOARD
    # Default: none
    clickEvent = ""

    # The command to run / suggest or the link to open
    # Default: None
    clickEventValue = ""

    # Add a hover event message to the message
    hoverEventText = ""

    # The message itself.
    # Supports:
        #  & - Color codes
        #  &#123456 - Hex color codes
    message = [

    ]


