# Configuration file for Dirt-Essentials

[general]
    # Wether debug-messages should be printed to the console (has some usefull information)
    # Default: true
    debug = true

    # The prefix of the /broadcast command message
    # Default: "&7[&cDirtCraft&7]"
    broadcastPrefix = "&7[&cDirtCraft&7]"

    # How many players are allowed to be on the server at the same time
    # INFO: Set the limit in the server.properties file to 999
    # Default: 999
    maxPlayers = 999

    # Can staff players join even if the server is full?
    # Default: true
    staffJoinFull = true

    # The message that is sent to the player when he tries to join a full server
    # Default: "&4The server is currently full!\n\n&cPlease try again later!"
    fullMessage = "&4The server is currently full!\n\n&cPlease try again later!"

    # The prefix character for nicknames
    # Default: "~"
    nicknamePrefix = "~"

    # After how many seconds are players marked as afk?
    # Default: 60
    afkTime = 60

    # Will players be kicked when they are afk for too long?
    # Default: true
    afkKick = true

    # After how many second will players be kicked once they are afk?
    # This will be ignored if the above value is set to true
    # Default: 240
    afkKickTime = 240

    # The message that is sent to the player when he is kicked for being afk
    # Default: "&4You have been kicked for being afk for too long!"
    afkKickMessage = "&4You have been kicked for being afk for too long!"

    # Worlds that people may or may not save the death point for /back
    # Default: ["world", "world/DIM1", "world/DIM-1"]
    backWorlds = [
        "world",
        "world/DIM1",
        "world/DIM-1"
    ]

    # Wether the above list should be a whitelist or a blacklist
    # Default: true
    backWorldsWhitelist = true


[economy]
    # The character to be used for the currency
    # Default: "$"
    currencySymbol = "$"

    # The default amount of money a player gets when he joins the server for the first time
    # Default: 800
    defaultMoney = 800

    # How many players should be displayed in the /baltop command?
    # Max: 15
    # Default: 10
    baltopSize = 10


[home]
    # The default amount of homes new players get.
    # Default: 1
    defaultHomes = 1

    # The cooldown for the /home command
    # The value is in seconds!
    # Default: 60
    homeCooldown = 60

    # How many homes should be displayed in the /homes command and the /ohomes command?
    # Max: 15
    # Default: 10
    homesSize = 10

[worth]
    # The identifier of the server
    # If this is empty the plugin will not fetch worth data
    name = ""
